### ISSUE TITLE
API Reference not present at typedi.js.org

### ISSUE THREAD

**Issue by bluelinden** [freshgum-bubbles/typedi#105]
Hi! I switched to this fork from upstream and I'm finding some of the APIs confusing, but that's beside the point. I went to the docs, and every doc link worked *except* for the API Reference. /api-reference returns a 404, in fact. Maybe it's related to this build error I get when i build the API reference using the typedoc command? I've run out of things to check on my end so I don't know whether it's an issue with this repo or not.

```
 ~/c/u/typedi  on develop  pnpm install && pnpm run docs:api-reference
Lockfile is up to date, resolution step is skipped
Packages: +772
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 0, reused 716, downloaded 0, added 772, done

> @freshgum/typedi@0.5.1 prepare /home/blue/code/utils/typedi
> husky install

husky - Git hooks installed
Done in 8s

> @freshgum/typedi@0.5.1 docs:api-reference /home/blue/code/utils/typedi
> rimraf website/build/api-reference && typedoc

[info] Loaded plugin @mxssfd/typedoc-theme
[warning] The entrypoint glob ./src/index.ts did not match any files.
[error] Unable to find any entry points. See previous warnings.
 ELIFECYCLE  Command failed with exit code 3.

 ~/c/u/typedi  on develop   
```
PNPM version: 8.7.0
Node version v18.17.0
typedi version: latest commit as of 10/03/23 10:26 EDT
(also tried with Bun package manager / runtime 1.0.3, didn't work either)

If there's a better way to read the API docs or compile them myself, please do let me know!

- blue 

EDIT: sorry for not clarifying, but i did try and fix all of the issues, like first changing the entrypoint, then setting the typedoc tsconfig to use the tsconfig.spec, however none of them ultimately solved the problems and it still threw dozens of compile errors relating to JSX usage and various unresolveable modules.

**Comment by freshgum-bubbles** [comment]
Oh hi! Sorry I missed this, looks like my notification settings were wrong.

The API Reference stuff in itself is a little touch and go; I don't 100% remember what happened with it,
but I distinctly remember finding it not really very good.  

That, combined with the fact that I'd *like* to implement API Extractor here, must have
caused me to hold off on the Typedoc idea at all.

Anyways, if someone finds it helpful, I'll have a look at it right now and get that `/api-reference/` base working.
Sorry it wasn't in the first place!

freshgum

**Comment by freshgum-bubbles** [comment]
[The *API Reference*](https://typedi.js.org/api-reference/) now works :-)

The fix was [fairly simple](https://github.com/freshgum-bubbles/typedi/commit/6bed06871fa8e460f6245dcdf84dbe65dd96b271), for the curious.  Bit of egg on my face.

> [...] I'm finding some of the APIs confusing, but that's beside the point.

It's not!  Feel free to open a new issue and I can talk you through the parts of the API you don't understand.
The API's designed to be *fairly* similar to that of the original TypeDI, but with a few notable QoL improvements.
Anyway, happy to help... :-)

> If there's a better way to read the API docs or compile them myself, please do let me know!

https://github.com/freshgum-bubbles/typedi/blob/72192d375147b3e528df33502f5fe42a1c71ad3f/package.json#L56

72192d375147b3e528df33502f5fe42a1c71ad3f sees the birth of a new "deploy docs" script.  While that's designed for deploying to https://typedi.js.org (by calling `docusaurus deploy`, etc.) it also gives an overview of how to compile the other parts of the website.

For *just* creating the API Reference locally, the `docs:api-reference` does what you need -- it emits the files to `docs/static/api-reference`.  You can either start a local server in `docs/static` (`python -m http.server`), or start a local development server for the Docusaurus website (with the [`docs:website`](https://github.com/freshgum-bubbles/typedi/blob/72192d375147b3e528df33502f5fe42a1c71ad3f/package.json#L55) script).

freshgum
