### ISSUE TITLE
Container not registering classes defined in external directories

### ISSUE THREAD

**Issue by 1gnacio** [freshgum-bubbles/typedi#138]
Hi, im having trouble trying to get the dependency injection to work if my files are in different directories

Im using the following structure for my project

usecases/
infrastructure/
entities/
web/

where `web` is a next js app
infrastructure is where I defined the following classes

```typescript
import { Service } from '@freshgum/typedi';
import IAuthService from "../../../usecases/common/interfaces/authService";
import type IGateway from "../interfaces/gateway";
import ApiGateway from '../gateways/gateway';


@Service({ scope: "transient" }, [ApiGateway])
export default class AuthService implements IAuthService {
    private readonly gateway : IGateway;

    /**
     *
     */
    constructor(gateway : IGateway) {
        this.gateway = gateway;
    }
}
```

```typescript
import IGateway from "../interfaces/gateway";
import { Service } from "@freshgum/typedi";

@Service({ scope: "singleton" }, [])
export default class ApiGateway implements IGateway {
    ...
}
```

*EDIT: I try to use this command inside a page of my next's project*

if I try to use `Container.get(AuthService);`

I get the following error

`ServiceNotFoundError: Service with "MaybeConstructable<AuthService>" identifier was not found in the container. Register it before usage via "Container.set" or the "@Service()" decorator.`

its the same error if I try to register it manually

```typescript
let identifier : ServiceIdentifier = AuthService;
if (!Container.has(identifier)) {
    identifier = Container.set(AuthService);
}
const service = Container.get(AuthService);
``` 

these are my dependencies in package.json file in /web

```
"dependencies": {
    "18": "^0.0.0",
    "@freshgum/typedi": "^0.6.0",
    "@headlessui/react": "^1.7.17",
    "@heroicons/react": "^2.0.18",
    "@tremor/react": "^3.6.6",
    "@types/react": "18.2.20",
    "@types/react-dom": "18.2.7",
    "@types/react-router-dom": "^5.3.3",
    "axios": "^1.5.1",
    "next": "13.5.6",
    "next-auth": "^4.23.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.48.2",
    "react-router-dom": "^6.17.0",
    "reflect-metadata": "^0.1.13",
    "sharp": "^0.32.6",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@types/node": "^20",
    "autoprefixer": "^10",
    "eslint": "^8",
    "eslint-config-next": "13.5.4",
    "postcss": "^8",
    "tailwindcss": "^3",
    "ts-loader": "^9.5.0",
    "typescript": "^5"
  }
```

and this is the `next.config.js` file

```
/** @type {import('next').NextConfig} */
const nextConfig = {
    images: {
        domains: ['avatars.githubusercontent.com', 'avatar.vercel.sh']
      },
    experimental: {
      serverActions: true,
      externalDir: true,
    },
    output: 'standalone',
}

module.exports = nextConfig
```

it works fine if dependencies are inside a directory, as I managed to write a test file in the infrastructure folder to try injecting them (although it only works with classes defined inside the infrastructure folder)

any advise on how can I make it work using multiple directories? thanks.

**Comment by freshgum-bubbles** [comment]
In theory, it *should* work fine in this scenario:  you've imported `AuthService`, so the `@Service(...)` call in `auth.service.ts` should run and it should then make itself available to the container.
This *seems* like something Next-specific, where service registration and service acquisition are being run in separate contexts (one on the server, one on the client).  I'm not familiar enough with Next's architecture to give any specific advice here.

(To be 100% sure, how are you importing `AuthService`?  It's not a global, is it? That *might* not work, depending upon how your app is structured.)

> `identifier = Container.set(AuthService);`

I do notice this, though: this is invalid.  [You need to provide `Container.set` with `ServiceOptions`](https://typedi.js.org/api-reference/classes/ContainerInstance.html#set) (or one of the many overloads) instead of just a bare constructor.
Some examples of this can be found in the documentation [here](https://typedi.js.org/docs/guide/tokens/introduction#setting-the-value-of-a-token) (I'll update the docs with a service-specific example, but just take that example and replace `MESSAGE` with `AuthService`, same with `value`.)

One thing I can think of that *might* be causing this is: Next.js might be importing multiple versions of the `@freshgum/typedi` package -- that wouldn't work, as your `AuthService` would be registered in one default container, while you're trying to attain it from a different one.
You could check this by iterating over your container's `metadataMap` to see which services are being registered.  Let the example ensue:

```ts
import { Container } from '@freshgum/typedi';
import type { ContainerInstance, ServiceIdentifier } from '@freshgum/typedi';

function inspectContainer (container: ContainerInstance) {
  let validIDs: ServiceIdentifier[] = [ ];

  // Iterate over each ID in the container, and add them to validIDs.
  for (const [id, metadata] of container) {
    validIDs.push(id);
  }

  return validIDs;
}

console.log(inspectContainer(Container));
// -> [ServiceIdentifier, ServiceIdentifier, ...]
```

*One small red flag here is that you're using `serverActions`, which seems to imply that it's running some JavaScript on the server.  What does your `AuthService` do?  Is it meant for the client-side, or the server-side?*

**Comment by 1gnacio** [comment]
Hi @freshgum-bubbles ! Thanks for the feedback, it was very useful. 

As I noticed doing some research about Nextjs lifecycle, in development mode sometimes the app does a refresh and it may collect all instances created in the container and destroying them. 

Also client and server components may use different containers, as I managed to implement a custom singleton class using Next globals and the original typedi, and only using the instances through server components.

I know my comment isn't precise about this issue and how I solved it, but Im almost at the deadline of this project and I need to use what is working right now, maybe in the future I will investigate this further and give a more detailed explanation.

Thanks again, keep it up.

**Comment by freshgum-bubbles** [comment]
> Also client and server components may use different containers, as I managed to implement a custom singleton class using Next globals and the original typedi, and only using the instances through server components.

Precautionary note to avoid using multiple DI containers :P

>  Im almost at the deadline of this project and I need to use what is working right now, maybe in the future I will investigate this further and give a more detailed explanation.

Yeah!  Might be useful for other Next.js users :)

> Thanks again, keep it up.

Glad I could help; feel free to report any other issues / questions :)
