### ISSUE TITLE
Confusion regarding arguments passed to service factory tuples

### ISSUE THREAD

**Issue by ikilobyte** [freshgum-bubbles/typedi#154]
**Describe the bug**
factory function with arguments，It's not the engine.
**To Reproduce**
```ts
import {Container, Service} from '@freshgum/typedi';

@Service([])
class Engine {
    public type = 'V8';

    public get name() : string {
        return 'bmw';
    }
}

@Service([Engine])
class CarFactory {
    createCar(engine: Engine) {
        console.log(engine);    // ContainerInstance not Engine
        engine.type = 'V6';
        return new Car(engine);
    }
}

@Service({ factory: [CarFactory, 'createCar'] }, [Engine])
class Car {
    constructor(public engine: Engine) {

    }
}

const car = Container.get(Car);
console.log(car.engine.type);
console.log(car.engine.name);  // undefined


```

- OS: `MacOS`
- Browser `Chrome`
- Version `^0.7.1`

**Comment by ikilobyte** [comment]
-  Parameters that you want to add directly to the factory，Similar to the following code, I wonder if it can be supported?
- code
```ts
import {Container, Service} from '@freshgum/typedi';
@Service([])
class Engine {
    public type = 'V8';

    public get name() : string {
        return 'bmw';
    }
}

@Service([Engine])
class CarFactory {
    createCar(container: ContainerInstance, id: ServiceIdentifier, parameters: DependencyDescriptor[],args?: any[]) {
        
        console.log(args); // ['foo','bar']

        return new Car(new Engine());
    }
}

//
// Hopefully, you can add parameters passed directly to the factory
@Service({ factory: [CarFactory, 'createCar',['foo','bar']] }, [Engine])
class Car {
    constructor(public engine: Engine) {

    }
}

**Comment by freshgum-bubbles** [comment]
```ts
@Service([Engine])
class CarFactory {
    createCar(engine: Engine) {
        console.log(engine);    // ContainerInstance not Engine
        engine.type = 'V6';
        return new Car(engine);
    }
}
```

In this case, your factory function signature is wrong.  If we look at the DI source code...

https://github.com/freshgum-bubbles/typedi/blob/867f2416938b7c9b1bc818faa2eacf54901f3674/src/container-instance.class.mts#L1292-L1297

...and evaluate that in our head, you'll come to realise that the DI container resolves your `CarFactory`
via the container itself.  In this case, as you've stated that `Engine` is a dependency of `CarFactory`,
you need to accept that via its constructor and then store it in a property.

Furthermore, for array syntax, the factory function is invoked with three arguments:
  1. The container itself (`ContainerInstance`)
  2. The ID of the service being created by the factory (`ServiceIdentifier`)
  3. The dependencies of the service, as an array of [`DependencyDescriptor`](https://github.com/freshgum-bubbles/typedi/blob/develop/src/interfaces/dependency-descriptor.interface.mts) objects.

<sup>Check your `ContainerInstance`'s `type` property after evaluating your factory function :)</sup>

As a general tip, prefer explicit function references as opposed to the magic tuple syntax;
that's largely just kept around to make it easier for typestack-based code-bases to migrate over, should they wish to.

---

> Parameters that you want to add directly to the factory

I'm unlikely to support this because it makes an already confusing operation even more so,
though if you provide some rational reasoning behind this, I may reconsider.

**Comment by freshgum-bubbles** [comment]
@ikilobyte Hiya, did you solve this issue afterwards?

P.S. [You seem to be making issues (some duplicates)](https://github.com/freshgum-bubbles/typedi/issues?q=is%3Aissue+author%3Aikilobyte+is%3Aclosed) and then never following-up / engaging with my responses.

So while I'm happy that you feel comfortable to ask questions (*which is a good thing!*), it would be awesome
if you could be more responsive after lodging them :-)

**Comment by ikilobyte** [comment]
@freshgum-bubbles 

I didn't solve this problem. Do you have any plans to support this feature?

I forgot to mention this before, so it caused duplication.

**Comment by freshgum-bubbles** [comment]
@ikilobyte I don't have plans to change this behaviour.  [My previous comment](https://github.com/freshgum-bubbles/typedi/issues/154#issuecomment-1879789530) provided a well-detailed explanation of what happens here, and where your code goes wrong :-)
